# Generated by Django 2.0 on 2021-05-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_bookingtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Image',
            field=models.FileField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='profile_pic',
            field=models.FileField(default='doc_male.png', upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.FileField(upload_to='img/'),
        ),
    ]
